### ISSUE TITLE
Implement full config management

### ISSUE THREAD

**Issue by jglista** [jglista/sqlizer#8]
Currently, the config subcommand only allows you to initialize a config. We should be able to update and remove specific entries. the config format should be able to support multiple RDBMS and multiple databases per entry. Something like this:

```yaml
sqlserver:
  dbhost:
    myDB:
      user: user
      pass: pass
    myOtherDB:
      user: user
      pass: pass
mysql:
  dbhost:
    someDB:
      user: user
      pass: pass
postgresql:
  dbhost:
    testDB:
      user: user
      pass: pass
```

This should allow us to more easily support many entries per database system.
